# Generated by Django 6.0.5 on 2026-06-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarehouseaccess',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='warehouse.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='userwarehouseaccess',
            unique_together={('user', 'warehouse')},
        ),
    ]
