# Generated by Django 6.0.5 on 2026-06-03 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_rename_status_managerassignment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWarehouseAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=True)),
                ('can_manage_stock', models.BooleanField(default=False)),
                ('can_transfer_stock', models.BooleanField(default=False)),
                ('can_manage_sales', models.BooleanField(default=False)),
                ('can_manage_installations', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_accesses', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'core_user_warehouse_access',
                'unique_together': {('user', 'warehouse')},
            },
        ),
    ]
