# Generated by Django 6.0.5 on 2026-05-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.citys', verbose_name='citys'),
        ),
    ]
