# Generated by Django 6.0.5 on 2026-06-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stockentryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockentryitem',
            name='stock_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='transferreception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferreception',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validated_receptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferreception',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reception', to='inventory.transfer'),
        ),
        migrations.AddField(
            model_name='transferreceptionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferreceptionitem',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferreception'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('product', 'warehouse')},
        ),
    ]
