# Generated by Django 6.0.5 on 2026-05-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_active_alter_warehouse_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='active',
            new_name='status',
        ),
    ]
