# Generated by Django 6.0.5 on 2026-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
