# Generated by Django 6.0.5 on 2026-05-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_active_warehouse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerassignment',
            old_name='is_active',
            new_name='status',
        ),
    ]
