# Generated by Django 6.0.5 on 2026-06-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transferreceptionitem_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_TRANSIT', 'En transit'), ('RECEIVED', 'Réceptionné'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_transfer', to='inventory.product'),
        ),
    ]
