# Generated by Django 6.0.5 on 2026-05-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_is_active_managerassignment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerassignment',
            old_name='status',
            new_name='is_active',
        ),
    ]
