# Generated by Django 6.0.5 on 2026-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_transfer_status_alter_transferitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
