# Generated by Django 6.0.5 on 2026-06-05 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_status_managerassignment_is_active'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(max_length=150)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='supplier_invoices/')),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('RECEIVED', 'Réceptionné'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='supplier.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_entries',
            },
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_items', to='inventory.product')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry')),
            ],
            options={
                'db_table': 'inventory_stock_entry_items',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_TRANSIT', 'En transit'), ('PARTIALLY_RECEIVED', 'Réception partielle'), ('RECEIVED', 'Réceptionné'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferReception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validated_receptions', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reception', to='inventory.transfer')),
            ],
            options={
                'db_table': 'inventory_transfer_receptions',
            },
        ),
        migrations.CreateModel(
            name='TransferReceptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RECEIVED', 'Reçu'), ('MISSING', 'Manquant'), ('DAMAGED', 'Endommagé')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferreception')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_transfer_reception_items',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.stockitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transfer')),
            ],
            options={
                'db_table': 'inventory_transfer_items',
                'unique_together': {('transfer', 'stock_item')},
            },
        ),
    ]
