# Generated by Django 6.0.5 on 2026-06-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockentry_stockentryitem_transfer_transferreception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
