# Generated by Django 6.0.5 on 2026-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KIT_STANDARD', 'kit standard'), ('KIT_MINI', 'kit mini')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
