# Generated by Django 6.0.5 on 2026-06-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KIT_STANDARD', 'kit standard'), ('KIT_MINI', 'kit mini'), ('AUTRES', 'Autres')], max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
