# Generated by Django 6.0.5 on 2026-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockentryitem_is_serialized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=True, verbose_name='Produit sérialisé'),
        ),
    ]
