# Generated by Django 6.0.5 on 2026-06-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_is_serialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentryitem',
            name='is_serialized',
        ),
    ]
