# Generated by Django 6.0.5 on 2026-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_stockentryitem_is_serialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
