# Generated by Django 6.0.5 on 2026-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_stockentry_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentryitem',
            name='quantity',
        ),
    ]
